### ISSUE TITLE
Can't install on Joomla

### ISSUE THREAD

**Issue by imagenparaweb** [juliopontes/staticcontent#9]
Hey, I just can't install it on my Joomla site, which runs ver 1.5.15.

I upload it, but it says: Error! Could not find a Joomla! XML setup file in the package.

Do you know why is that?

Thanks!!

**Comment by WooDzu** [comment]
Joomla 1.5.15 is not supported any more by the Joomla team and 99% of extension developers.
Why not upgrade?

**Comment by imagenparaweb** [comment]
You're right.. I'm moving now to v2.5. Is that ok?
Is it compatible with that version?

Thanks WooDzu

**Comment by juliopontes** [comment]
Yep its for Joomla! 2.5+. But not tested on latest version

**Comment by imagenparaweb** [comment]
You mean you don't know if it works on Joomla 3.4.4?

**Comment by WooDzu** [comment]
Worked well on 3.4.3 when I tested last time

**Comment by imagenparaweb** [comment]
Thanks buddy-

**Comment by robscure** [comment]
Hello, I have an old joomla on 1.5.22. Upgrading is exactly what I am trying to avoid, would like to get the static html and then get rid of the joomla alltogether. Any suggestions if the staticcontent could be changed so that it works on 1.5.X instead of throwing the "Error! Could not find a Joomla! XML setup file in the package. "
